### ISSUE TITLE
Tweak: Disable status update autocomplete

### ISSUE THREAD

**Issue by matthewbrandt** [jschuur/coworking.party#69]
I didn't click into the status bar field, for some reason the tooltip gets shown on its own.
![Screenshot 2024-05-07 at 11 01 07](https://github.com/jschuur/coworking.party/assets/67697593/fbb6fbd3-09e7-4b15-8258-fbeed19c05f1)

**Comment by jschuur** [comment]
@matthewbrandt I think this is just the '[autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete)' feature of the browser. I don't use any tooltips on that field.

I don't actually get this in Chrome but I've seen it occasionally in Safari.

Is this even useful? Maybe in the edge case of wanting to fix a typo. Maybe it's better disabled entirely?

**Comment by matthewbrandt** [comment]
If I could choose I would remove it entirely, yes.

**Comment by jschuur** [comment]
[Done](https://github.com/jschuur/coworking.party/commit/aec7fa16ddf102db3e601a947f5ec7f4ccf064c3)
